#!/bin/bash
ls -a ~/dotfiles/ | grep -v "\.git$" | grep -v "setup" | grep -v "txt" | grep -v ^"\."$ | grep -v ^"\.\."$ > ~/files.txt
while read -r line
do
	rm ~/"$line" &>/dev/null
	ln -s ~/dotfiles/"$line" ~/"$line"
done < ~/files.txt
rm ~/files.txt
echo "Finished creating symlinks!"
source ~/.bashrc
